export const SET_SINGER = 'SET_SINGER';
export const SET_PLAYLIST = 'SET_PLAYLIST';
export const SET_CURRENT_INDEX = 'SET_CURRENT_INDEX';
export const SET_PLAYSTATE = 'SET_PLAYSTATE';
export const SET_SEQUENCE_LIST = 'SET_SEQUENCE_LIST';
export const SET_FULL_PLAY = 'SET_FULL_PLAY';
export const SET_MINI_PLAY = 'SET_MINI_PLAY';
export const SET_CURRENTSONG = 'SET_CURRENTSONG';